# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MP Cloud Design System
email: hello@ninelabs.com
description: >- # this means to ignore newlines until "baseurl:"
  Brand and Design Standards for MP Cloud and EMTech
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ninelabs
github_username:  ninelabs

# Build settings
markdown: kramdown

kramdown:
    auto_ids: true
    entity_output: as_char
    toc_levels: [2, 3, 4, 5, 6]
    smart_quotes: lsquo,rsquo,ldquo,rdquo
    input: GFM
    hard_wrap: false
    footnote_nr: 1
    show_warnings: false

highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
